server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;
    server_tokens "off";

    location / {
        # Optimized for large file upload/download.
        sendfile on;
        output_buffers 2 512k;
        aio on;
        client_max_body_size 0;
        tcp_nopush on;
        tcp_nodelay on;

        root   /usr/share/nginx/html;
        index  index.html index.htm;
        autoindex on;
        autoindex_format json;

        dav_methods PUT DELETE;
        dav_access user:rw group:r all:r;
        create_full_put_path on;
    }
}
