definitions:
  handlers.S3Credentials:
    properties:
      accessKeyId:
        type: string
      expiration:
        type: string
      secretAccessKey:
        type: string
      sessionToken:
        type: string
    type: object
info:
  contact: {}
  description: This is the API for the EODHP Workspace Services.
  title: EODHP Workspace Services API
  version: v1
paths:
  /workspaces/{workspace-id}/users/{user-id}/s3-tokens:
    get:
      consumes:
      - application/json
      description: Request S3 session credentials for user access to a single workspace
      parameters:
      - description: Workspace ID
        in: path
        name: workspace-id
        required: true
        type: string
      - description: User ID
        in: path
        name: user-id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.S3Credentials'
        "400":
          description: Bad Request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Request S3 session credentials
      tags:
      - s3 credentials auth
swagger: "2.0"
