name: Build and Publish Docker Image

on:
  push:
    tags:
      - v[0-9]+*
    branches:
      - main
jobs:
  security-scan:
    name: Call Security Scan
    uses: EO-DataHub/github-actions/.github/workflows/security.yaml@main
  tag:
    name: Extract Docker image tag
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{steps.tag.outputs.tag}}
    steps:
      - id: tag
        run: |
          if [[ ${{github.ref_name}} == main ]]; then
            echo tag=latest >> $GITHUB_OUTPUT
          else
            echo tag=$(echo ${{github.ref_name}} | sed 's/^v//') >> $GITHUB_OUTPUT
          fi
      - run: echo tag=${{steps.tag.outputs.tag}}
  publish:
    name: Build and push Docker image
    needs: tag
    if: ${{vars.IMAGE_NAME}} != ""
    uses: EO-DataHub/github-actions/.github/workflows/docker-image-to-aws-ecr.yaml@main
    with:
      image_name: ${{vars.IMAGE_NAME}}
      image_tag: ${{needs.tag.outputs.image_tag}}
    permissions:
      id-token: write
      contents: read
    secrets:
      AWS_ACCOUNT_ID: ${{vars.AWS_ACCOUNT_ID}}
      AWS_ECR: ${{vars.AWS_ECR}}
      AWS_REGION: ${{vars.AWS_REGION}}
    
      
    
