name: Build and Publish Docker Image

on:
  push:
    tags:
      - v[0-9]+*
    branches:
      - main
jobs:
  security-scan:
    name: Call Security Scan
    uses: EO-DataHub/github-actions/.github/workflows/security.yaml@main
  tag:
    uses: EO-DataHub/github-actions/.github/workflows/get-docker-tag.yaml@main
    with:
      github-ref: ${{ github.ref_name}}
  publish:
    name: Build and push Docker image
    needs: tag
    if: ${{ vars.IMAGE_NAME }} != ""
    uses: EO-DataHub/github-actions/.github/workflows/docker-image-to-aws-ecr.yaml@main
    with:
      image_name: ${{ vars.IMAGE_NAME }}
      image_tag: ${{ needs.tag.outputs.image-tag }}
    permissions:
      id-token: write
      contents: read
    secrets:
      AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
      AWS_ECR: ${{ vars.AWS_ECR }}
      AWS_REGION: ${{ vars.AWS_REGION }}
