name: Go Build and Test

on: [push]

permissions:
  contents: read

jobs:
  go-build:
    uses: EO-DataHub/github-actions/.github/workflows/go-build.yaml@main
    with:
      go-version: "1.22"
      coverage-threshold-file: 0      
      coverage-threshold-package: 0    
      coverage-threshold-total: 0  
